import fs from 'fs/promises';
import path from 'path';

export async function writeTestFile(
  baseDir: string,
  targetFilePath: string,
  symbolName: string,
  testCode: string
): Promise<string> {
  const testsDir = path.join(baseDir, 'tests', 'unit');
  await fs.mkdir(testsDir, { recursive: true });

  const ext = path.extname(targetFilePath) || '.js';
  const baseName = path.basename(targetFilePath, ext);
  
  // Use symbolName if it's not the entire file to avoid overwriting file-level tests
  let safeSymbol = symbolName === 'entire-file' ? '' : `-${symbolName.replace(/[^a-zA-Z0-9]/g, '')}`;
  if (safeSymbol === '-') safeSymbol = '';
  
  // Choose TS extension if original is TS
  const testExt = ext.includes('ts') ? '.test.ts' : '.test.js';
  const testFileName = `${baseName}${safeSymbol}${testExt}`;
  const testFilePath = path.join(testsDir, testFileName);

  await fs.writeFile(testFilePath, testCode, 'utf8');
  return testFilePath;
}

export async function writeJestSetup(baseDir: string): Promise<void> {
  const jestConfigPath = path.join(baseDir, 'jest.config.js');
  const jestConfigContent = `module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/tests/**/*.test.[jt]s?(x)'],
  transform: {
    '^.+\\\\.tsx?$': 'ts-jest',
    '^.+\\\\.jsx?$': 'babel-jest',
  }
};
`;
  await fs.writeFile(jestConfigPath, jestConfigContent, 'utf8');
}

export async function writeReadme(baseDir: string): Promise<void> {
  const readmePath = path.join(baseDir, 'README_TESTING.md');
  const readmeContent = `# Testing Guide

This folder and testing setup were automatically generated by **TestPilot** 🚀.

## Folder Structure
- \`/tests/unit/\`: Contains all the isolated unit tests generated by the AI agent.
- \`jest.config.js\`: Configuration for running the tests using Jest.

## Setup Instructions

Make sure you have installed the required dependencies to run the generated tests:

\`\`\`bash
npm install -D jest @types/jest ts-jest babel-jest @babel/preset-env @babel/preset-typescript
\`\`\`

*(Ensure your \`package.json\` has a test script: \`"test": "jest"\`)*

## Running Tests

To execute all tests in the project, simply run:

\`\`\`bash
npm run test
\`\`\`

To run a specific test file:
\`\`\`bash
npx jest tests/unit/example.test.ts
\`\`\`

## Notes
- These tests were generated using \`qwen2.5-coder:3b\` with semantic context retrieved via ChromaDB (\`nomic-embed-text\`).
- Always review AI-generated tests to ensure they correctly capture your business logic expectations!
`;
  await fs.writeFile(readmePath, readmeContent, 'utf8');
}